services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  # device:
  #   build: ../device-service
  #   env_file:
  #     - ../.env
  #   ports:
  #     - "${DEVICE_PORT}:8080"
  #   depends_on:
  #     - postgres

  # sensor:
  #   build: ../sensor-service
  #   env_file:
  #     - ../.env
  #   ports:
  #     - "${SENSOR_PORT}:8082"
  #   depends_on:
  #     - postgres

volumes:
  db_data:
