services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mertani
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  device:
    build: ../device-service
    environment:
      - DATABASE_DSN=host=postgres user=postgres password=admin dbname=mertani port=5432 sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  sensor:
    build: ../sensor-service
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/mertani
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=admin
    ports:
      - "8082:8082"
    depends_on:
      - postgres

volumes:
  db_data:
